// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<
  ffi.Pointer<llama_token> Function(ffi.Pointer<llama_adapter_lora>)
>()
external ffi.Pointer<llama_token> llama_adapter_get_alora_invocation_tokens(
  ffi.Pointer<llama_adapter_lora> adapter,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<llama_adapter_lora>)>()
external int llama_adapter_get_alora_n_invocation_tokens(
  ffi.Pointer<llama_adapter_lora> adapter,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_adapter_lora>)>()
external void llama_adapter_lora_free(ffi.Pointer<llama_adapter_lora> adapter);

@ffi.Native<
  ffi.Pointer<llama_adapter_lora> Function(
    ffi.Pointer<llama_model>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<llama_adapter_lora> llama_adapter_lora_init(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> path_lora,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_adapter_lora>)>()
external int llama_adapter_meta_count(ffi.Pointer<llama_adapter_lora> adapter);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_adapter_lora>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_adapter_meta_key_by_index(
  ffi.Pointer<llama_adapter_lora> adapter,
  int i,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_adapter_lora>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_adapter_meta_val_str(
  ffi.Pointer<llama_adapter_lora> adapter,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_adapter_lora>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_adapter_meta_val_str_by_index(
  ffi.Pointer<llama_adapter_lora> adapter,
  int i,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>)>()
external bool llama_add_bos_token(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>)>()
external bool llama_add_eos_token(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<llama_context>,
    ggml_threadpool_t,
    ggml_threadpool_t,
  )
>()
external void llama_attach_threadpool(
  ffi.Pointer<llama_context> ctx,
  ggml_threadpool_t threadpool,
  ggml_threadpool_t threadpool_batch,
);

@ffi.Native<ffi.Void Function()>()
external void llama_backend_free();

@ffi.Native<ffi.Void Function()>()
external void llama_backend_init();

@ffi.Native<ffi.Void Function(llama_batch)>()
external void llama_batch_free(llama_batch batch);

@ffi.Native<llama_batch Function(ffi.Pointer<llama_token>, ffi.Int32)>()
external llama_batch llama_batch_get_one(
  ffi.Pointer<llama_token> tokens,
  int n_tokens,
);

@ffi.Native<llama_batch Function(ffi.Int32, ffi.Int32, ffi.Int32)>()
external llama_batch llama_batch_init(int n_tokens, int embd, int n_seq_max);

/// Apply chat template. Inspired by hf apply_chat_template() on python.
///
/// NOTE: This function does not use a jinja parser. It only support a pre-defined list of template. See more: https://github.com/ggml-org/llama.cpp/wiki/Templates-supported-by-llama_chat_apply_template
/// @param tmpl A Jinja template to use for this chat.
/// @param chat Pointer to a list of multiple llama_chat_message
/// @param n_msg Number of llama_chat_message in this chat
/// @param add_ass Whether to end the prompt with the token(s) that indicate the start of an assistant message.
/// @param buf A buffer to hold the output formatted prompt. The recommended alloc size is 2 * (total number of characters of all messages)
/// @param length The size of the allocated buffer
/// @return The total number of bytes of the formatted prompt. If is it larger than the size of buffer, you may need to re-alloc it and then re-apply the template.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_chat_message>,
    ffi.Size,
    ffi.Bool,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
  )
>()
external int llama_chat_apply_template(
  ffi.Pointer<ffi.Char> tmpl,
  ffi.Pointer<llama_chat_message> chat,
  int n_msg,
  bool add_ass,
  ffi.Pointer<ffi.Char> buf,
  int length,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Pointer<ffi.Char>>, ffi.Size)>()
external int llama_chat_builtin_templates(
  ffi.Pointer<ffi.Pointer<ffi.Char>> output,
  int len,
);

@ffi.Native<llama_context_params Function()>()
external llama_context_params llama_context_default_params();

@ffi.Native<
  ffi.Size Function(ffi.Pointer<llama_context>, ffi.Pointer<ffi.Uint8>)
>()
external int llama_copy_state_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> dst,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_context>, llama_batch)>()
external int llama_decode(ffi.Pointer<llama_context> ctx, llama_batch batch);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_detach_threadpool(ffi.Pointer<llama_context> ctx);

/// @details Convert the provided tokens into text (inverse of llama_tokenize()).
/// @param text The char pointer must be large enough to hold the resulting text.
/// @return Returns the number of chars/bytes on success, no more than text_len_max.
/// @return Returns a negative number on failure - the number of chars/bytes that would have been returned.
/// @param remove_special Allow to remove BOS and EOS tokens if model is configured to do so.
/// @param unparse_special If true, special tokens are rendered in the output.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<llama_token>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Bool,
    ffi.Bool,
  )
>()
external int llama_detokenize(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<llama_token> tokens,
  int n_tokens,
  ffi.Pointer<ffi.Char> text,
  int text_len_max,
  bool remove_special,
  bool unparse_special,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_context>, llama_batch)>()
external int llama_encode(ffi.Pointer<llama_context> ctx, llama_batch batch);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Int)>(
  symbol: 'llama_flash_attn_type_name',
)
external ffi.Pointer<ffi.Char> _llama_flash_attn_type_name(int flash_attn_type);

ffi.Pointer<ffi.Char> llama_flash_attn_type_name(
  llama_flash_attn_type flash_attn_type,
) => _llama_flash_attn_type_name(flash_attn_type.value);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_free(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_model>)>()
external void llama_free_model(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>)>()
external ffi.Pointer<ffi.Float> llama_get_embeddings(
  ffi.Pointer<llama_context> ctx,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, ffi.Int32)
>()
external ffi.Pointer<ffi.Float> llama_get_embeddings_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, llama_seq_id)
>()
external ffi.Pointer<ffi.Float> llama_get_embeddings_seq(
  ffi.Pointer<llama_context> ctx,
  int seq_id,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>)>()
external ffi.Pointer<ffi.Float> llama_get_logits(
  ffi.Pointer<llama_context> ctx,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, ffi.Int32)
>()
external ffi.Pointer<ffi.Float> llama_get_logits_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<llama_memory_t Function(ffi.Pointer<llama_context>)>()
external llama_memory_t llama_get_memory(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Pointer<llama_model> Function(ffi.Pointer<llama_context>)>()
external ffi.Pointer<llama_model> llama_get_model(
  ffi.Pointer<llama_context> ctx,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>, ffi.Int32)>()
external int llama_get_sampled_candidates_count_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<
  ffi.Pointer<llama_token> Function(ffi.Pointer<llama_context>, ffi.Int32)
>()
external ffi.Pointer<llama_token> llama_get_sampled_candidates_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>, ffi.Int32)>()
external int llama_get_sampled_logits_count_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, ffi.Int32)
>()
external ffi.Pointer<ffi.Float> llama_get_sampled_logits_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>, ffi.Int32)>()
external int llama_get_sampled_probs_count_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<
  ffi.Pointer<ffi.Float> Function(ffi.Pointer<llama_context>, ffi.Int32)
>()
external ffi.Pointer<ffi.Float> llama_get_sampled_probs_ith(
  ffi.Pointer<llama_context> ctx,
  int i,
);

@ffi.Native<llama_token Function(ffi.Pointer<llama_context>, ffi.Int32)>()
external int llama_get_sampled_token_ith(ffi.Pointer<llama_context> ctx, int i);

@ffi.Native<ffi.Size Function(ffi.Pointer<llama_context>)>()
external int llama_get_state_size(ffi.Pointer<llama_context> ctx);

@ffi.Native<
  ffi.Pointer<llama_context> Function(
    ffi.Pointer<llama_model>,
    llama_context_params,
  )
>()
external ffi.Pointer<llama_context> llama_init_from_model(
  ffi.Pointer<llama_model> model,
  llama_context_params params,
);

@ffi.Native<
  ffi.Pointer<llama_model> Function(ffi.Pointer<ffi.Char>, llama_model_params)
>()
external ffi.Pointer<llama_model> llama_load_model_from_file(
  ffi.Pointer<ffi.Char> path_model,
  llama_model_params params,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_token>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external bool llama_load_session_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> path_session,
  ffi.Pointer<llama_token> tokens_out,
  int n_token_capacity,
  ffi.Pointer<ffi.Size> n_token_count_out,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ggml_log_callback>,
    ffi.Pointer<ffi.Pointer<ffi.Void>>,
  )
>()
external void llama_log_get(
  ffi.Pointer<ggml_log_callback> log_callback,
  ffi.Pointer<ffi.Pointer<ffi.Void>> user_data,
);

@ffi.Native<ffi.Void Function(ggml_log_callback, ffi.Pointer<ffi.Void>)>()
external void llama_log_set(
  ggml_log_callback log_callback,
  ffi.Pointer<ffi.Void> user_data,
);

@ffi.Native<ffi.Size Function()>()
external int llama_max_devices();

@ffi.Native<ffi.Size Function()>()
external int llama_max_parallel_sequences();

@ffi.Native<ffi.Size Function()>()
external int llama_max_tensor_buft_overrides();

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_memory_breakdown_print(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Bool Function(llama_memory_t)>()
external bool llama_memory_can_shift(llama_memory_t mem);

@ffi.Native<ffi.Void Function(llama_memory_t, ffi.Bool)>()
external void llama_memory_clear(llama_memory_t mem, bool data);

@ffi.Native<
  ffi.Void Function(
    llama_memory_t,
    llama_seq_id,
    llama_pos,
    llama_pos,
    llama_pos,
  )
>()
external void llama_memory_seq_add(
  llama_memory_t mem,
  int seq_id,
  int p0,
  int p1,
  int delta,
);

@ffi.Native<
  ffi.Void Function(
    llama_memory_t,
    llama_seq_id,
    llama_seq_id,
    llama_pos,
    llama_pos,
  )
>()
external void llama_memory_seq_cp(
  llama_memory_t mem,
  int seq_id_src,
  int seq_id_dst,
  int p0,
  int p1,
);

@ffi.Native<
  ffi.Void Function(llama_memory_t, llama_seq_id, llama_pos, llama_pos, ffi.Int)
>()
external void llama_memory_seq_div(
  llama_memory_t mem,
  int seq_id,
  int p0,
  int p1,
  int d,
);

@ffi.Native<ffi.Void Function(llama_memory_t, llama_seq_id)>()
external void llama_memory_seq_keep(llama_memory_t mem, int seq_id);

@ffi.Native<llama_pos Function(llama_memory_t, llama_seq_id)>()
external int llama_memory_seq_pos_max(llama_memory_t mem, int seq_id);

@ffi.Native<llama_pos Function(llama_memory_t, llama_seq_id)>()
external int llama_memory_seq_pos_min(llama_memory_t mem, int seq_id);

@ffi.Native<
  ffi.Bool Function(llama_memory_t, llama_seq_id, llama_pos, llama_pos)
>()
external bool llama_memory_seq_rm(
  llama_memory_t mem,
  int seq_id,
  int p0,
  int p1,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<llama_model>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<ffi.Char> llama_model_chat_template(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> name,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<llama_model>, ffi.Uint32)
>()
external ffi.Pointer<ffi.Char> llama_model_cls_label(
  ffi.Pointer<llama_model> model,
  int i,
);

@ffi.Native<llama_token Function(ffi.Pointer<llama_model>)>()
external int llama_model_decoder_start_token(ffi.Pointer<llama_model> model);

@ffi.Native<llama_model_params Function()>()
external llama_model_params llama_model_default_params();

@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<llama_model>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int llama_model_desc(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_model>)>()
external void llama_model_free(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Pointer<llama_vocab> Function(ffi.Pointer<llama_model>)>()
external ffi.Pointer<llama_vocab> llama_model_get_vocab(
  ffi.Pointer<llama_model> model,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_model>)>()
external bool llama_model_has_decoder(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_model>)>()
external bool llama_model_has_encoder(ffi.Pointer<llama_model> model);

@ffi.Native<
  ffi.Pointer<llama_model> Function(
    ffi.Pointer<gguf_context>,
    llama_model_set_tensor_data_t,
    ffi.Pointer<ffi.Void>,
    llama_model_params,
  )
>()
external ffi.Pointer<llama_model> llama_model_init_from_user(
  ffi.Pointer<gguf_context> metadata,
  llama_model_set_tensor_data_t set_tensor_data,
  ffi.Pointer<ffi.Void> set_tensor_data_ud,
  llama_model_params params,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_model>)>()
external bool llama_model_is_diffusion(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_model>)>()
external bool llama_model_is_hybrid(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_model>)>()
external bool llama_model_is_recurrent(ffi.Pointer<llama_model> model);

@ffi.Native<
  ffi.Pointer<llama_model> Function(ffi.Pointer<ffi.Char>, llama_model_params)
>()
external ffi.Pointer<llama_model> llama_model_load_from_file(
  ffi.Pointer<ffi.Char> path_model,
  llama_model_params params,
);

@ffi.Native<
  ffi.Pointer<llama_model> Function(ffi.Pointer<FILE>, llama_model_params)
>()
external ffi.Pointer<llama_model> llama_model_load_from_file_ptr(
  ffi.Pointer<FILE> file,
  llama_model_params params,
);

@ffi.Native<
  ffi.Pointer<llama_model> Function(
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    llama_model_params,
  )
>()
external ffi.Pointer<llama_model> llama_model_load_from_splits(
  ffi.Pointer<ffi.Pointer<ffi.Char>> paths,
  int n_paths,
  llama_model_params params,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_meta_count(ffi.Pointer<llama_model> model);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_model>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_model_meta_key_by_index(
  ffi.Pointer<llama_model> model,
  int i,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.UnsignedInt)>(
  symbol: 'llama_model_meta_key_str',
)
external ffi.Pointer<ffi.Char> _llama_model_meta_key_str(int key);

ffi.Pointer<ffi.Char> llama_model_meta_key_str(llama_model_meta_key key) =>
    _llama_model_meta_key_str(key.value);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_model>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_model_meta_val_str(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> key,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_model>,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int llama_model_meta_val_str_by_index(
  ffi.Pointer<llama_model> model,
  int i,
  ffi.Pointer<ffi.Char> buf,
  int buf_size,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_cls_out(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_ctx_train(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_embd(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_embd_inp(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_embd_out(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_head(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_head_kv(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_layer(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_params(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_model_n_swa(ffi.Pointer<llama_model> model);

@ffi.Native<
  ffi.Uint32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_model_quantize_params>,
  )
>()
external int llama_model_quantize(
  ffi.Pointer<ffi.Char> fname_inp,
  ffi.Pointer<ffi.Char> fname_out,
  ffi.Pointer<llama_model_quantize_params> params,
);

@ffi.Native<llama_model_quantize_params Function()>()
external llama_model_quantize_params llama_model_quantize_default_params();

@ffi.Native<ffi.Float Function(ffi.Pointer<llama_model>)>()
external double llama_model_rope_freq_scale_train(
  ffi.Pointer<llama_model> model,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<llama_model>)>(
  symbol: 'llama_model_rope_type',
)
external int _llama_model_rope_type(ffi.Pointer<llama_model> model);

llama_rope_type llama_model_rope_type(ffi.Pointer<llama_model> model) =>
    llama_rope_type.fromValue(_llama_model_rope_type(model));

@ffi.Native<
  ffi.Void Function(ffi.Pointer<llama_model>, ffi.Pointer<ffi.Char>)
>()
external void llama_model_save_to_file(
  ffi.Pointer<llama_model> model,
  ffi.Pointer<ffi.Char> path_model,
);

@ffi.Native<ffi.Uint64 Function(ffi.Pointer<llama_model>)>()
external int llama_model_size(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_batch(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_ctx(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_ctx_seq(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_n_ctx_train(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_n_embd(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_n_head(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_model>)>()
external int llama_n_layer(ffi.Pointer<llama_model> model);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_seq_max(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_threads(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_threads_batch(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_context>)>()
external int llama_n_ubatch(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_vocab>)>()
external int llama_n_vocab(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<
  ffi.Pointer<llama_context> Function(
    ffi.Pointer<llama_model>,
    llama_context_params,
  )
>()
external ffi.Pointer<llama_context> llama_new_context_with_model(
  ffi.Pointer<llama_model> model,
  llama_context_params params,
);

@ffi.Native<ffi.Void Function(ffi.UnsignedInt)>(symbol: 'llama_numa_init')
external void _llama_numa_init(int numa);

void llama_numa_init(ggml_numa_strategy numa) => _llama_numa_init(numa.value);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<llama_context>,
    ggml_opt_dataset_t,
    ggml_opt_result_t,
    ggml_opt_result_t,
    ffi.Int64,
    ggml_opt_epoch_callback,
    ggml_opt_epoch_callback,
  )
>()
external void llama_opt_epoch(
  ffi.Pointer<llama_context> lctx,
  ggml_opt_dataset_t dataset,
  ggml_opt_result_t result_train,
  ggml_opt_result_t result_eval,
  int idata_split,
  ggml_opt_epoch_callback callback_train,
  ggml_opt_epoch_callback callback_eval,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<llama_model>,
    llama_opt_params,
  )
>()
external void llama_opt_init(
  ffi.Pointer<llama_context> lctx,
  ffi.Pointer<llama_model> model,
  llama_opt_params lopt_params,
);

@ffi.Native<
  ffi.Bool Function(ffi.Pointer<ggml_tensor>, ffi.Pointer<ffi.Void>)
>()
external bool llama_opt_param_filter_all(
  ffi.Pointer<ggml_tensor> tensor,
  ffi.Pointer<ffi.Void> userdata,
);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_model_params>,
    ffi.Pointer<llama_context_params>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<llama_model_tensor_buft_override>,
    ffi.Pointer<ffi.Size>,
    ffi.Uint32,
    ffi.UnsignedInt,
  )
>(symbol: 'llama_params_fit')
external int _llama_params_fit(
  ffi.Pointer<ffi.Char> path_model,
  ffi.Pointer<llama_model_params> mparams,
  ffi.Pointer<llama_context_params> cparams,
  ffi.Pointer<ffi.Float> tensor_split,
  ffi.Pointer<llama_model_tensor_buft_override> tensor_buft_overrides,
  ffi.Pointer<ffi.Size> margins,
  int n_ctx_min,
  int log_level,
);

llama_params_fit_status llama_params_fit(
  ffi.Pointer<ffi.Char> path_model,
  ffi.Pointer<llama_model_params> mparams,
  ffi.Pointer<llama_context_params> cparams,
  ffi.Pointer<ffi.Float> tensor_split,
  ffi.Pointer<llama_model_tensor_buft_override> tensor_buft_overrides,
  ffi.Pointer<ffi.Size> margins,
  int n_ctx_min,
  ggml_log_level log_level,
) => llama_params_fit_status.fromValue(
  _llama_params_fit(
    path_model,
    mparams,
    cparams,
    tensor_split,
    tensor_buft_overrides,
    margins,
    n_ctx_min,
    log_level.value,
  ),
);

@ffi.Native<llama_perf_context_data Function(ffi.Pointer<llama_context>)>()
external llama_perf_context_data llama_perf_context(
  ffi.Pointer<llama_context> ctx,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_perf_context_print(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_perf_context_reset(ffi.Pointer<llama_context> ctx);

@ffi.Native<llama_perf_sampler_data Function(ffi.Pointer<llama_sampler>)>()
external llama_perf_sampler_data llama_perf_sampler(
  ffi.Pointer<llama_sampler> chain,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>)>()
external void llama_perf_sampler_print(ffi.Pointer<llama_sampler> chain);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>)>()
external void llama_perf_sampler_reset(ffi.Pointer<llama_sampler> chain);

@ffi.Native<ffi.Int Function(ffi.Pointer<llama_context>)>(
  symbol: 'llama_pooling_type',
)
external int _llama_pooling_type$1(ffi.Pointer<llama_context> ctx);

llama_pooling_type llama_pooling_type$1(ffi.Pointer<llama_context> ctx) =>
    llama_pooling_type.fromValue(_llama_pooling_type$1(ctx));

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> llama_print_system_info();

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>, llama_token)>()
external void llama_sampler_accept(ffi.Pointer<llama_sampler> smpl, int token);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<llama_sampler>,
    ffi.Pointer<llama_token_data_array>,
  )
>()
external void llama_sampler_apply(
  ffi.Pointer<llama_sampler> smpl,
  ffi.Pointer<llama_token_data_array> cur_p,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<llama_sampler>, ffi.Pointer<llama_sampler>)
>()
external void llama_sampler_chain_add(
  ffi.Pointer<llama_sampler> chain,
  ffi.Pointer<llama_sampler> smpl,
);

@ffi.Native<llama_sampler_chain_params Function()>()
external llama_sampler_chain_params llama_sampler_chain_default_params();

@ffi.Native<
  ffi.Pointer<llama_sampler> Function(ffi.Pointer<llama_sampler>, ffi.Int32)
>()
external ffi.Pointer<llama_sampler> llama_sampler_chain_get(
  ffi.Pointer<llama_sampler> chain,
  int i,
);

@ffi.Native<ffi.Pointer<llama_sampler> Function(llama_sampler_chain_params)>()
external ffi.Pointer<llama_sampler> llama_sampler_chain_init(
  llama_sampler_chain_params params,
);

@ffi.Native<ffi.Int Function(ffi.Pointer<llama_sampler>)>()
external int llama_sampler_chain_n(ffi.Pointer<llama_sampler> chain);

@ffi.Native<
  ffi.Pointer<llama_sampler> Function(ffi.Pointer<llama_sampler>, ffi.Int32)
>()
external ffi.Pointer<llama_sampler> llama_sampler_chain_remove(
  ffi.Pointer<llama_sampler> chain,
  int i,
);

@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Pointer<llama_sampler>)>()
external ffi.Pointer<llama_sampler> llama_sampler_clone(
  ffi.Pointer<llama_sampler> smpl,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>)>()
external void llama_sampler_free(ffi.Pointer<llama_sampler> smpl);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<llama_sampler>)>()
external int llama_sampler_get_seed(ffi.Pointer<llama_sampler> smpl);

@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Pointer<llama_sampler_i>,
    llama_sampler_context_t,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init(
  ffi.Pointer<llama_sampler_i> iface,
  llama_sampler_context_t ctx,
);

/// adaptive-p: select tokens near a configurable target probability over time.
///
/// the adaptive-p sampler transforms the token probability distribution to favor tokens
/// that fall near a user-configurable probability target.
///
/// internally, the sampler maintains an exponential moving average of the *ORIGINAL*
/// probabilities of selected tokens at each sampling step. it uses this EMA to compute an
/// adapted target probability at each sampling step, thus maintaining the desired target
/// probability over time.
///
/// adaptive-p selects a token ID rather than just mutating candidates, so it must be last
/// in the sampler chain (like mirostat, dist, greedy).
///
/// only mild truncation before this sampler is recommended. we suggest applying min-p
/// before adaptive-p as the only other active sampler in the chain.
///
/// @param target select tokens near this probability (valid range 0.0 to 1.0; negative = disabled)
/// @param decay  EMA decay for adaptation; history ≈ 1/(1-decay) tokens (valid range 0.0 - 0.99)
/// @param seed   RNG seed
///
/// ref: https://github.com/ggml-org/llama.cpp/pull/17927
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Float, ffi.Uint32)
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_adaptive_p(
  double target,
  double decay,
  int seed,
);

/// seed == LLAMA_DEFAULT_SEED to use a random seed.
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Uint32)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_dist(int seed);

/// @details DRY sampler, designed by p-e-w, as described in: https://github.com/oobabooga/text-generation-webui/pull/5677, porting Koboldcpp implementation authored by pi6am: https://github.com/LostRuins/koboldcpp/pull/982
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Pointer<llama_vocab>,
    ffi.Int32,
    ffi.Float,
    ffi.Float,
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_dry(
  ffi.Pointer<llama_vocab> vocab,
  int n_ctx_train,
  double dry_multiplier,
  double dry_base,
  int dry_allowed_length,
  int dry_penalty_last_n,
  ffi.Pointer<ffi.Pointer<ffi.Char>> seq_breakers,
  int num_breakers,
);

/// @details Initializes a GBNF grammar, see grammars/README.md for details.
/// @param vocab The vocabulary that this grammar will be used with.
/// @param grammar_str The production rules for the grammar, encoded as a string. Returns an empty grammar if empty. Returns NULL if parsing of grammar_str fails.
/// @param grammar_root The name of the start symbol for the grammar.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_grammar(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<ffi.Char> grammar_str,
  ffi.Pointer<ffi.Char> grammar_root,
);

@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Pointer<llama_token>,
    ffi.Size,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_grammar_lazy(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<ffi.Char> grammar_str,
  ffi.Pointer<ffi.Char> grammar_root,
  ffi.Pointer<ffi.Pointer<ffi.Char>> trigger_words,
  int num_trigger_words,
  ffi.Pointer<llama_token> trigger_tokens,
  int num_trigger_tokens,
);

/// @details Lazy grammar sampler, introduced in https://github.com/ggml-org/llama.cpp/pull/9639
/// @param trigger_patterns A list of patterns that will trigger the grammar sampler. Pattern will be matched from the start of the generation output, and grammar sampler will be fed content starting from its first match group.
/// @param trigger_tokens A list of tokens that will trigger the grammar sampler. Grammar sampler will be fed content starting from the trigger token included.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Size,
    ffi.Pointer<llama_token>,
    ffi.Size,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_grammar_lazy_patterns(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<ffi.Char> grammar_str,
  ffi.Pointer<ffi.Char> grammar_root,
  ffi.Pointer<ffi.Pointer<ffi.Char>> trigger_patterns,
  int num_trigger_patterns,
  ffi.Pointer<llama_token> trigger_tokens,
  int num_trigger_tokens,
);

@ffi.Native<ffi.Pointer<llama_sampler> Function()>()
external ffi.Pointer<llama_sampler> llama_sampler_init_greedy();

@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Pointer<llama_vocab>)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_infill(
  ffi.Pointer<llama_vocab> vocab,
);

@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Int32,
    ffi.Int32,
    ffi.Pointer<llama_logit_bias>,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_logit_bias(
  int n_vocab,
  int n_logit_bias,
  ffi.Pointer<llama_logit_bias> logit_bias,
);

/// @details Minimum P sampling as described in https://github.com/ggml-org/llama.cpp/pull/3841
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_min_p(
  double p,
  int min_keep,
);

/// @details Mirostat 1.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.
/// @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.
/// @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.
/// @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.
/// @param m The number of tokens considered in the estimation of `s_hat`. This is an arbitrary value that is used to calculate `s_hat`, which in turn helps to calculate the value of `k`. In the paper, they use `m = 100`, but you can experiment with different values to see how it affects the performance of the algorithm.
/// @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Int32,
    ffi.Uint32,
    ffi.Float,
    ffi.Float,
    ffi.Int32,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_mirostat(
  int n_vocab,
  int seed,
  double tau,
  double eta,
  int m,
);

/// @details Mirostat 2.0 algorithm described in the paper https://arxiv.org/abs/2007.14966. Uses tokens instead of words.
/// @param candidates A vector of `llama_token_data` containing the candidate tokens, their probabilities (p), and log-odds (logit) for the current position in the generated text.
/// @param tau  The target cross-entropy (or surprise) value you want to achieve for the generated text. A higher value corresponds to more surprising or less predictable text, while a lower value corresponds to less surprising or more predictable text.
/// @param eta The learning rate used to update `mu` based on the error between the target and observed surprisal of the sampled word. A larger learning rate will cause `mu` to be updated more quickly, while a smaller learning rate will result in slower updates.
/// @param mu Maximum cross-entropy. This value is initialized to be twice the target cross-entropy (`2 * tau`) and is updated in the algorithm based on the error between the target and observed surprisal.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(ffi.Uint32, ffi.Float, ffi.Float)
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_mirostat_v2(
  int seed,
  double tau,
  double eta,
);

/// NOTE: Avoid using on the full vocabulary as searching for repeated tokens can become slow. For example, apply top-k or top-p sampling first.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Int32,
    ffi.Float,
    ffi.Float,
    ffi.Float,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_penalties(
  int penalty_last_n,
  double penalty_repeat,
  double penalty_freq,
  double penalty_present,
);

/// #details Updates the logits l_i` = l_i/t. When t <= 0.0f, the maximum logit is kept at it's original value, the rest are set to -inf
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_temp(double t);

/// @details Dynamic temperature implementation (a.k.a. entropy) described in the paper https://arxiv.org/abs/2309.02772.
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Float, ffi.Float)
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_temp_ext(
  double t,
  double delta,
  double exponent,
);

/// @details Top-K sampling described in academic paper "The Curious Case of Neural Text Degeneration" https://arxiv.org/abs/1904.09751
/// Setting k <= 0 makes this a noop
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Int32)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_top_k(int k);

/// @details Top n sigma sampling as described in academic paper "Top-nσ: Not All Logits Are You Need" https://arxiv.org/pdf/2411.07641
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_top_n_sigma(double n);

/// @details Nucleus sampling described in academic paper "The Curious Case of Neural Text Degeneration" https://arxiv.org/abs/1904.09751
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_top_p(
  double p,
  int min_keep,
);

/// @details Locally Typical Sampling implementation described in the paper https://arxiv.org/abs/2202.00666.
@ffi.Native<ffi.Pointer<llama_sampler> Function(ffi.Float, ffi.Size)>()
external ffi.Pointer<llama_sampler> llama_sampler_init_typical(
  double p,
  int min_keep,
);

/// @details XTC sampler as described in https://github.com/oobabooga/text-generation-webui/pull/6335
@ffi.Native<
  ffi.Pointer<llama_sampler> Function(
    ffi.Float,
    ffi.Float,
    ffi.Size,
    ffi.Uint32,
  )
>()
external ffi.Pointer<llama_sampler> llama_sampler_init_xtc(
  double p,
  double t,
  int min_keep,
  int seed,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<llama_sampler>)>()
external ffi.Pointer<ffi.Char> llama_sampler_name(
  ffi.Pointer<llama_sampler> smpl,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_sampler>)>()
external void llama_sampler_reset(ffi.Pointer<llama_sampler> smpl);

@ffi.Native<
  llama_token Function(
    ffi.Pointer<llama_sampler>,
    ffi.Pointer<llama_context>,
    ffi.Int32,
  )
>()
external int llama_sampler_sample(
  ffi.Pointer<llama_sampler> smpl,
  ffi.Pointer<llama_context> ctx,
  int idx,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_token>,
    ffi.Size,
  )
>()
external bool llama_save_session_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> path_session,
  ffi.Pointer<llama_token> tokens,
  int n_token_count,
);

@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<llama_context>,
    ggml_abort_callback,
    ffi.Pointer<ffi.Void>,
  )
>()
external void llama_set_abort_callback(
  ffi.Pointer<llama_context> ctx,
  ggml_abort_callback abort_callback,
  ffi.Pointer<ffi.Void> abort_callback_data,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Float>,
    ffi.Size,
    ffi.Int32,
    ffi.Int32,
    ffi.Int32,
  )
>()
external int llama_set_adapter_cvec(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Float> data,
  int len,
  int n_embd,
  int il_start,
  int il_end,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Pointer<llama_adapter_lora>>,
    ffi.Size,
    ffi.Pointer<ffi.Float>,
  )
>()
external int llama_set_adapters_lora(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Pointer<llama_adapter_lora>> adapters,
  int n_adapters,
  ffi.Pointer<ffi.Float> scales,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>, ffi.Bool)>()
external void llama_set_causal_attn(
  ffi.Pointer<llama_context> ctx,
  bool causal_attn,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>, ffi.Bool)>()
external void llama_set_embeddings(
  ffi.Pointer<llama_context> ctx,
  bool embeddings,
);

@ffi.Native<
  ffi.Void Function(ffi.Pointer<llama_context>, ffi.Int32, ffi.Int32)
>()
external void llama_set_n_threads(
  ffi.Pointer<llama_context> ctx,
  int n_threads,
  int n_threads_batch,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<llama_context>,
    llama_seq_id,
    ffi.Pointer<llama_sampler>,
  )
>()
external bool llama_set_sampler(
  ffi.Pointer<llama_context> ctx,
  int seq_id,
  ffi.Pointer<llama_sampler> smpl,
);

@ffi.Native<
  ffi.Size Function(ffi.Pointer<llama_context>, ffi.Pointer<ffi.Uint8>)
>()
external int llama_set_state_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> src,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>, ffi.Bool)>()
external void llama_set_warmup(ffi.Pointer<llama_context> ctx, bool warmup);

/// @details Build a split GGUF final path for this chunk.
/// llama_split_path(split_path, sizeof(split_path), "/models/ggml-model-q4_0", 2, 4) => split_path = "/models/ggml-model-q4_0-00002-of-00004.gguf"
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Int32,
  )
>()
external int llama_split_path(
  ffi.Pointer<ffi.Char> split_path,
  int maxlen,
  ffi.Pointer<ffi.Char> path_prefix,
  int split_no,
  int split_count,
);

/// @details Extract the path prefix from the split_path if and only if the split_no and split_count match.
/// llama_split_prefix(split_prefix, 64, "/models/ggml-model-q4_0-00002-of-00004.gguf", 2, 4) => split_prefix = "/models/ggml-model-q4_0"
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Int32,
  )
>()
external int llama_split_prefix(
  ffi.Pointer<ffi.Char> split_prefix,
  int maxlen,
  ffi.Pointer<ffi.Char> split_path,
  int split_no,
  int split_count,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int llama_state_get_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> dst,
  int size,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<llama_context>)>()
external int llama_state_get_size(ffi.Pointer<llama_context> ctx);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_token>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external bool llama_state_load_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> path_session,
  ffi.Pointer<llama_token> tokens_out,
  int n_token_capacity,
  ffi.Pointer<ffi.Size> n_token_count_out,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<llama_token>,
    ffi.Size,
  )
>()
external bool llama_state_save_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> path_session,
  ffi.Pointer<llama_token> tokens,
  int n_token_count,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    llama_seq_id,
  )
>()
external int llama_state_seq_get_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> dst,
  int size,
  int seq_id,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    llama_seq_id,
    llama_state_seq_flags,
  )
>()
external int llama_state_seq_get_data_ext(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> dst,
  int size,
  int seq_id,
  int flags,
);

@ffi.Native<ffi.Size Function(ffi.Pointer<llama_context>, llama_seq_id)>()
external int llama_state_seq_get_size(
  ffi.Pointer<llama_context> ctx,
  int seq_id,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    llama_seq_id,
    llama_state_seq_flags,
  )
>()
external int llama_state_seq_get_size_ext(
  ffi.Pointer<llama_context> ctx,
  int seq_id,
  int flags,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    llama_seq_id,
    ffi.Pointer<llama_token>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int llama_state_seq_load_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> filepath,
  int dest_seq_id,
  ffi.Pointer<llama_token> tokens_out,
  int n_token_capacity,
  ffi.Pointer<ffi.Size> n_token_count_out,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Char>,
    llama_seq_id,
    ffi.Pointer<llama_token>,
    ffi.Size,
  )
>()
external int llama_state_seq_save_file(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Char> filepath,
  int seq_id,
  ffi.Pointer<llama_token> tokens,
  int n_token_count,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    llama_seq_id,
  )
>()
external int llama_state_seq_set_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> src,
  int size,
  int dest_seq_id,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
    llama_seq_id,
    llama_state_seq_flags,
  )
>()
external int llama_state_seq_set_data_ext(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> src,
  int size,
  int dest_seq_id,
  int flags,
);

@ffi.Native<
  ffi.Size Function(
    ffi.Pointer<llama_context>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Size,
  )
>()
external int llama_state_set_data(
  ffi.Pointer<llama_context> ctx,
  ffi.Pointer<ffi.Uint8> src,
  int size,
);

@ffi.Native<ffi.Bool Function()>()
external bool llama_supports_gpu_offload();

@ffi.Native<ffi.Bool Function()>()
external bool llama_supports_mlock();

@ffi.Native<ffi.Bool Function()>()
external bool llama_supports_mmap();

@ffi.Native<ffi.Bool Function()>()
external bool llama_supports_rpc();

@ffi.Native<ffi.Void Function(ffi.Pointer<llama_context>)>()
external void llama_synchronize(ffi.Pointer<llama_context> ctx);

@ffi.Native<ffi.Int64 Function()>()
external int llama_time_us();

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_bos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_cls(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_eos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_eot(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_mid(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_pad(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_pre(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_rep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_sep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_fim_suf(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_vocab>, llama_token)>(
  symbol: 'llama_token_get_attr',
)
external int _llama_token_get_attr(ffi.Pointer<llama_vocab> vocab, int token);

llama_token_attr llama_token_get_attr(
  ffi.Pointer<llama_vocab> vocab,
  Dartllama_token token,
) => llama_token_attr.fromValue(_llama_token_get_attr(vocab, token));

@ffi.Native<ffi.Float Function(ffi.Pointer<llama_vocab>, llama_token)>()
external double llama_token_get_score(
  ffi.Pointer<llama_vocab> vocab,
  int token,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<llama_vocab>, llama_token)
>()
external ffi.Pointer<ffi.Char> llama_token_get_text(
  ffi.Pointer<llama_vocab> vocab,
  int token,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>, llama_token)>()
external bool llama_token_is_control(ffi.Pointer<llama_vocab> vocab, int token);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>, llama_token)>()
external bool llama_token_is_eog(ffi.Pointer<llama_vocab> vocab, int token);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_nl(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_pad(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_token_sep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_vocab>,
    llama_token,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Int32,
    ffi.Bool,
  )
>()
external int llama_token_to_piece(
  ffi.Pointer<llama_vocab> vocab,
  int token,
  ffi.Pointer<ffi.Char> buf,
  int length,
  int lstrip,
  bool special,
);

/// @details Convert the provided text into tokens.
/// @param tokens The tokens pointer must be large enough to hold the resulting tokens.
/// @return Returns the number of tokens on success, no more than n_tokens_max
/// @return Returns a negative number on failure - the number of tokens that would have been returned
/// @return Returns INT32_MIN on overflow (e.g., tokenization result size exceeds int32_t limit)
/// @param add_special Allow to add BOS and EOS tokens if model is configured to do so.
/// @param parse_special Allow tokenizing special and/or control tokens which otherwise are not exposed and treated
/// as plaintext. Does not insert a leading space.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<llama_vocab>,
    ffi.Pointer<ffi.Char>,
    ffi.Int32,
    ffi.Pointer<llama_token>,
    ffi.Int32,
    ffi.Bool,
    ffi.Bool,
  )
>()
external int llama_tokenize(
  ffi.Pointer<llama_vocab> vocab,
  ffi.Pointer<ffi.Char> text,
  int text_len,
  ffi.Pointer<llama_token> tokens,
  int n_tokens_max,
  bool add_special,
  bool parse_special,
);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_bos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_cls(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_eos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_eot(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_mid(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_pad(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_pre(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_rep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_sep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_fim_suf(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>)>()
external bool llama_vocab_get_add_bos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>)>()
external bool llama_vocab_get_add_eos(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>)>()
external bool llama_vocab_get_add_sep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_vocab>, llama_token)>(
  symbol: 'llama_vocab_get_attr',
)
external int _llama_vocab_get_attr(ffi.Pointer<llama_vocab> vocab, int token);

llama_token_attr llama_vocab_get_attr(
  ffi.Pointer<llama_vocab> vocab,
  Dartllama_token token,
) => llama_token_attr.fromValue(_llama_vocab_get_attr(vocab, token));

@ffi.Native<ffi.Float Function(ffi.Pointer<llama_vocab>, llama_token)>()
external double llama_vocab_get_score(
  ffi.Pointer<llama_vocab> vocab,
  int token,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<llama_vocab>, llama_token)
>()
external ffi.Pointer<ffi.Char> llama_vocab_get_text(
  ffi.Pointer<llama_vocab> vocab,
  int token,
);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>, llama_token)>()
external bool llama_vocab_is_control(ffi.Pointer<llama_vocab> vocab, int token);

@ffi.Native<ffi.Bool Function(ffi.Pointer<llama_vocab>, llama_token)>()
external bool llama_vocab_is_eog(ffi.Pointer<llama_vocab> vocab, int token);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_mask(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_n_tokens(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_nl(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_pad(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<llama_token Function(ffi.Pointer<llama_vocab>)>()
external int llama_vocab_sep(ffi.Pointer<llama_vocab> vocab);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<llama_vocab>)>(
  symbol: 'llama_vocab_type',
)
external int _llama_vocab_type$1(ffi.Pointer<llama_vocab> vocab);

llama_vocab_type llama_vocab_type$1(ffi.Pointer<llama_vocab> vocab) =>
    llama_vocab_type.fromValue(_llama_vocab_type$1(vocab));

typedef FILE = __sFILE;

const int LLAMA_DEFAULT_SEED = 4294967295;

const int LLAMA_FILE_MAGIC_GGLA = 1734831201;

const int LLAMA_FILE_MAGIC_GGSN = 1734833006;

const int LLAMA_FILE_MAGIC_GGSQ = 1734833009;

const int LLAMA_SESSION_MAGIC = 1734833006;

const int LLAMA_SESSION_VERSION = 9;

const int LLAMA_STATE_SEQ_FLAGS_PARTIAL_ONLY = 1;

const int LLAMA_STATE_SEQ_FLAGS_SWA_ONLY = 1;

const int LLAMA_STATE_SEQ_MAGIC = 1734833009;

const int LLAMA_STATE_SEQ_VERSION = 2;

const int LLAMA_TOKEN_NULL = -1;

final class UnnamedStruct extends ffi.Struct {
  @ffi.Float()
  external double alpha;

  @ffi.Float()
  external double beta1;

  @ffi.Float()
  external double beta2;

  @ffi.Float()
  external double eps;

  @ffi.Float()
  external double wd;
}

final class UnnamedStruct$1 extends ffi.Struct {
  @ffi.Float()
  external double alpha;

  @ffi.Float()
  external double wd;
}

final class UnnamedUnion extends ffi.Union {
  @ffi.Int64()
  external int val_i64;

  @ffi.Double()
  external double val_f64;

  @ffi.Bool()
  external bool val_bool;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> val_str;
}

typedef __darwin_off_t = __int64_t;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;

final class __sFILE extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _p;

  @ffi.Int()
  external int _r;

  @ffi.Int()
  external int _w;

  @ffi.Short()
  external int _flags;

  @ffi.Short()
  external int _file;

  external __sbuf _bf;

  @ffi.Int()
  external int _lbfsize;

  external ffi.Pointer<ffi.Void> _cookie;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Void>)>
  >
  _close;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)
    >
  >
  _read;

  external ffi.Pointer<
    ffi.NativeFunction<fpos_t Function(ffi.Pointer<ffi.Void>, fpos_t, ffi.Int)>
  >
  _seek;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Int Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Int)
    >
  >
  _write;

  external __sbuf _ub;

  external ffi.Pointer<__sFILEX> _extra;

  @ffi.Int()
  external int _ur;

  @ffi.Array.multi([3])
  external ffi.Array<ffi.UnsignedChar> _ubuf;

  @ffi.Array.multi([1])
  external ffi.Array<ffi.UnsignedChar> _nbuf;

  external __sbuf _lb;

  @ffi.Int()
  external int _blksize;

  @fpos_t()
  external int _offset;
}

final class __sFILEX extends ffi.Opaque {}

final class __sbuf extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedChar> _base;

  @ffi.Int()
  external int _size;
}

typedef fpos_t = __darwin_off_t;
typedef ggml_abort_callback =
    ffi.Pointer<ffi.NativeFunction<ggml_abort_callbackFunction>>;
typedef ggml_abort_callbackFunction =
    ffi.Bool Function(ffi.Pointer<ffi.Void> data);
typedef Dartggml_abort_callbackFunction =
    bool Function(ffi.Pointer<ffi.Void> data);

final class ggml_backend_buffer extends ffi.Opaque {}

final class ggml_backend_buffer_type extends ffi.Opaque {}

typedef ggml_backend_buffer_type_t = ffi.Pointer<ggml_backend_buffer_type>;
typedef ggml_backend_dev_t = ffi.Pointer<ggml_backend_device>;

final class ggml_backend_device extends ffi.Opaque {}

typedef ggml_backend_sched_eval_callback =
    ffi.Pointer<ffi.NativeFunction<ggml_backend_sched_eval_callbackFunction>>;
typedef ggml_backend_sched_eval_callbackFunction =
    ffi.Bool Function(
      ffi.Pointer<ggml_tensor> t,
      ffi.Bool ask,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef Dartggml_backend_sched_eval_callbackFunction =
    bool Function(
      ffi.Pointer<ggml_tensor> t,
      bool ask,
      ffi.Pointer<ffi.Void> user_data,
    );

final class ggml_cgraph extends ffi.Opaque {}

final class ggml_context extends ffi.Opaque {}

typedef ggml_log_callback =
    ffi.Pointer<ffi.NativeFunction<ggml_log_callbackFunction>>;
typedef ggml_log_callbackFunction =
    ffi.Void Function(
      ffi.UnsignedInt level,
      ffi.Pointer<ffi.Char> text,
      ffi.Pointer<ffi.Void> user_data,
    );
typedef Dartggml_log_callbackFunction =
    void Function(
      ggml_log_level level,
      ffi.Pointer<ffi.Char> text,
      ffi.Pointer<ffi.Void> user_data,
    );

enum ggml_log_level {
  GGML_LOG_LEVEL_NONE(0),
  GGML_LOG_LEVEL_DEBUG(1),
  GGML_LOG_LEVEL_INFO(2),
  GGML_LOG_LEVEL_WARN(3),
  GGML_LOG_LEVEL_ERROR(4),
  GGML_LOG_LEVEL_CONT(5);

  final int value;
  const ggml_log_level(this.value);

  static ggml_log_level fromValue(int value) => switch (value) {
    0 => GGML_LOG_LEVEL_NONE,
    1 => GGML_LOG_LEVEL_DEBUG,
    2 => GGML_LOG_LEVEL_INFO,
    3 => GGML_LOG_LEVEL_WARN,
    4 => GGML_LOG_LEVEL_ERROR,
    5 => GGML_LOG_LEVEL_CONT,
    _ => throw ArgumentError('Unknown value for ggml_log_level: $value'),
  };
}

enum ggml_numa_strategy {
  GGML_NUMA_STRATEGY_DISABLED(0),
  GGML_NUMA_STRATEGY_DISTRIBUTE(1),
  GGML_NUMA_STRATEGY_ISOLATE(2),
  GGML_NUMA_STRATEGY_NUMACTL(3),
  GGML_NUMA_STRATEGY_MIRROR(4),
  GGML_NUMA_STRATEGY_COUNT(5);

  final int value;
  const ggml_numa_strategy(this.value);

  static ggml_numa_strategy fromValue(int value) => switch (value) {
    0 => GGML_NUMA_STRATEGY_DISABLED,
    1 => GGML_NUMA_STRATEGY_DISTRIBUTE,
    2 => GGML_NUMA_STRATEGY_ISOLATE,
    3 => GGML_NUMA_STRATEGY_NUMACTL,
    4 => GGML_NUMA_STRATEGY_MIRROR,
    5 => GGML_NUMA_STRATEGY_COUNT,
    _ => throw ArgumentError('Unknown value for ggml_numa_strategy: $value'),
  };
}

enum ggml_op {
  GGML_OP_NONE(0),
  GGML_OP_DUP(1),
  GGML_OP_ADD(2),
  GGML_OP_ADD_ID(3),
  GGML_OP_ADD1(4),
  GGML_OP_ACC(5),
  GGML_OP_SUB(6),
  GGML_OP_MUL(7),
  GGML_OP_DIV(8),
  GGML_OP_SQR(9),
  GGML_OP_SQRT(10),
  GGML_OP_LOG(11),
  GGML_OP_SIN(12),
  GGML_OP_COS(13),
  GGML_OP_SUM(14),
  GGML_OP_SUM_ROWS(15),
  GGML_OP_CUMSUM(16),
  GGML_OP_MEAN(17),
  GGML_OP_ARGMAX(18),
  GGML_OP_COUNT_EQUAL(19),
  GGML_OP_REPEAT(20),
  GGML_OP_REPEAT_BACK(21),
  GGML_OP_CONCAT(22),
  GGML_OP_SILU_BACK(23),
  GGML_OP_NORM(24),
  GGML_OP_RMS_NORM(25),
  GGML_OP_RMS_NORM_BACK(26),
  GGML_OP_GROUP_NORM(27),
  GGML_OP_L2_NORM(28),
  GGML_OP_MUL_MAT(29),
  GGML_OP_MUL_MAT_ID(30),
  GGML_OP_OUT_PROD(31),
  GGML_OP_SCALE(32),
  GGML_OP_SET(33),
  GGML_OP_CPY(34),
  GGML_OP_CONT(35),
  GGML_OP_RESHAPE(36),
  GGML_OP_VIEW(37),
  GGML_OP_PERMUTE(38),
  GGML_OP_TRANSPOSE(39),
  GGML_OP_GET_ROWS(40),
  GGML_OP_GET_ROWS_BACK(41),
  GGML_OP_SET_ROWS(42),
  GGML_OP_DIAG(43),
  GGML_OP_DIAG_MASK_INF(44),
  GGML_OP_DIAG_MASK_ZERO(45),
  GGML_OP_SOFT_MAX(46),
  GGML_OP_SOFT_MAX_BACK(47),
  GGML_OP_ROPE(48),
  GGML_OP_ROPE_BACK(49),
  GGML_OP_CLAMP(50),
  GGML_OP_CONV_TRANSPOSE_1D(51),
  GGML_OP_IM2COL(52),
  GGML_OP_IM2COL_BACK(53),
  GGML_OP_IM2COL_3D(54),
  GGML_OP_CONV_2D(55),
  GGML_OP_CONV_3D(56),
  GGML_OP_CONV_2D_DW(57),
  GGML_OP_CONV_TRANSPOSE_2D(58),
  GGML_OP_POOL_1D(59),
  GGML_OP_POOL_2D(60),
  GGML_OP_POOL_2D_BACK(61),
  GGML_OP_UPSCALE(62),
  GGML_OP_PAD(63),
  GGML_OP_PAD_REFLECT_1D(64),
  GGML_OP_ROLL(65),
  GGML_OP_ARANGE(66),
  GGML_OP_TIMESTEP_EMBEDDING(67),
  GGML_OP_ARGSORT(68),
  GGML_OP_TOP_K(69),
  GGML_OP_LEAKY_RELU(70),
  GGML_OP_TRI(71),
  GGML_OP_FILL(72),
  GGML_OP_FLASH_ATTN_EXT(73),
  GGML_OP_FLASH_ATTN_BACK(74),
  GGML_OP_SSM_CONV(75),
  GGML_OP_SSM_SCAN(76),
  GGML_OP_WIN_PART(77),
  GGML_OP_WIN_UNPART(78),
  GGML_OP_GET_REL_POS(79),
  GGML_OP_ADD_REL_POS(80),
  GGML_OP_RWKV_WKV6(81),
  GGML_OP_GATED_LINEAR_ATTN(82),
  GGML_OP_RWKV_WKV7(83),
  GGML_OP_SOLVE_TRI(84),
  GGML_OP_GATED_DELTA_NET(85),
  GGML_OP_UNARY(86),
  GGML_OP_MAP_CUSTOM1(87),
  GGML_OP_MAP_CUSTOM2(88),
  GGML_OP_MAP_CUSTOM3(89),
  GGML_OP_CUSTOM(90),
  GGML_OP_CROSS_ENTROPY_LOSS(91),
  GGML_OP_CROSS_ENTROPY_LOSS_BACK(92),
  GGML_OP_OPT_STEP_ADAMW(93),
  GGML_OP_OPT_STEP_SGD(94),
  GGML_OP_GLU(95),
  GGML_OP_COUNT(96);

  final int value;
  const ggml_op(this.value);

  static ggml_op fromValue(int value) => switch (value) {
    0 => GGML_OP_NONE,
    1 => GGML_OP_DUP,
    2 => GGML_OP_ADD,
    3 => GGML_OP_ADD_ID,
    4 => GGML_OP_ADD1,
    5 => GGML_OP_ACC,
    6 => GGML_OP_SUB,
    7 => GGML_OP_MUL,
    8 => GGML_OP_DIV,
    9 => GGML_OP_SQR,
    10 => GGML_OP_SQRT,
    11 => GGML_OP_LOG,
    12 => GGML_OP_SIN,
    13 => GGML_OP_COS,
    14 => GGML_OP_SUM,
    15 => GGML_OP_SUM_ROWS,
    16 => GGML_OP_CUMSUM,
    17 => GGML_OP_MEAN,
    18 => GGML_OP_ARGMAX,
    19 => GGML_OP_COUNT_EQUAL,
    20 => GGML_OP_REPEAT,
    21 => GGML_OP_REPEAT_BACK,
    22 => GGML_OP_CONCAT,
    23 => GGML_OP_SILU_BACK,
    24 => GGML_OP_NORM,
    25 => GGML_OP_RMS_NORM,
    26 => GGML_OP_RMS_NORM_BACK,
    27 => GGML_OP_GROUP_NORM,
    28 => GGML_OP_L2_NORM,
    29 => GGML_OP_MUL_MAT,
    30 => GGML_OP_MUL_MAT_ID,
    31 => GGML_OP_OUT_PROD,
    32 => GGML_OP_SCALE,
    33 => GGML_OP_SET,
    34 => GGML_OP_CPY,
    35 => GGML_OP_CONT,
    36 => GGML_OP_RESHAPE,
    37 => GGML_OP_VIEW,
    38 => GGML_OP_PERMUTE,
    39 => GGML_OP_TRANSPOSE,
    40 => GGML_OP_GET_ROWS,
    41 => GGML_OP_GET_ROWS_BACK,
    42 => GGML_OP_SET_ROWS,
    43 => GGML_OP_DIAG,
    44 => GGML_OP_DIAG_MASK_INF,
    45 => GGML_OP_DIAG_MASK_ZERO,
    46 => GGML_OP_SOFT_MAX,
    47 => GGML_OP_SOFT_MAX_BACK,
    48 => GGML_OP_ROPE,
    49 => GGML_OP_ROPE_BACK,
    50 => GGML_OP_CLAMP,
    51 => GGML_OP_CONV_TRANSPOSE_1D,
    52 => GGML_OP_IM2COL,
    53 => GGML_OP_IM2COL_BACK,
    54 => GGML_OP_IM2COL_3D,
    55 => GGML_OP_CONV_2D,
    56 => GGML_OP_CONV_3D,
    57 => GGML_OP_CONV_2D_DW,
    58 => GGML_OP_CONV_TRANSPOSE_2D,
    59 => GGML_OP_POOL_1D,
    60 => GGML_OP_POOL_2D,
    61 => GGML_OP_POOL_2D_BACK,
    62 => GGML_OP_UPSCALE,
    63 => GGML_OP_PAD,
    64 => GGML_OP_PAD_REFLECT_1D,
    65 => GGML_OP_ROLL,
    66 => GGML_OP_ARANGE,
    67 => GGML_OP_TIMESTEP_EMBEDDING,
    68 => GGML_OP_ARGSORT,
    69 => GGML_OP_TOP_K,
    70 => GGML_OP_LEAKY_RELU,
    71 => GGML_OP_TRI,
    72 => GGML_OP_FILL,
    73 => GGML_OP_FLASH_ATTN_EXT,
    74 => GGML_OP_FLASH_ATTN_BACK,
    75 => GGML_OP_SSM_CONV,
    76 => GGML_OP_SSM_SCAN,
    77 => GGML_OP_WIN_PART,
    78 => GGML_OP_WIN_UNPART,
    79 => GGML_OP_GET_REL_POS,
    80 => GGML_OP_ADD_REL_POS,
    81 => GGML_OP_RWKV_WKV6,
    82 => GGML_OP_GATED_LINEAR_ATTN,
    83 => GGML_OP_RWKV_WKV7,
    84 => GGML_OP_SOLVE_TRI,
    85 => GGML_OP_GATED_DELTA_NET,
    86 => GGML_OP_UNARY,
    87 => GGML_OP_MAP_CUSTOM1,
    88 => GGML_OP_MAP_CUSTOM2,
    89 => GGML_OP_MAP_CUSTOM3,
    90 => GGML_OP_CUSTOM,
    91 => GGML_OP_CROSS_ENTROPY_LOSS,
    92 => GGML_OP_CROSS_ENTROPY_LOSS_BACK,
    93 => GGML_OP_OPT_STEP_ADAMW,
    94 => GGML_OP_OPT_STEP_SGD,
    95 => GGML_OP_GLU,
    96 => GGML_OP_COUNT,
    _ => throw ArgumentError('Unknown value for ggml_op: $value'),
  };
}

final class ggml_opt_context extends ffi.Opaque {}

typedef ggml_opt_context_t = ffi.Pointer<ggml_opt_context>;

final class ggml_opt_dataset extends ffi.Opaque {}

typedef ggml_opt_dataset_t = ffi.Pointer<ggml_opt_dataset>;
typedef ggml_opt_epoch_callback =
    ffi.Pointer<ffi.NativeFunction<ggml_opt_epoch_callbackFunction>>;
typedef ggml_opt_epoch_callbackFunction =
    ffi.Void Function(
      ffi.Bool train,
      ggml_opt_context_t opt_ctx,
      ggml_opt_dataset_t dataset,
      ggml_opt_result_t result,
      ffi.Int64 ibatch,
      ffi.Int64 ibatch_max,
      ffi.Int64 t_start_us,
    );
typedef Dartggml_opt_epoch_callbackFunction =
    void Function(
      bool train,
      ggml_opt_context_t opt_ctx,
      ggml_opt_dataset_t dataset,
      ggml_opt_result_t result,
      int ibatch,
      int ibatch_max,
      int t_start_us,
    );
typedef ggml_opt_get_optimizer_params =
    ffi.Pointer<ffi.NativeFunction<ggml_opt_get_optimizer_paramsFunction>>;
typedef ggml_opt_get_optimizer_paramsFunction =
    ggml_opt_optimizer_params Function(ffi.Pointer<ffi.Void> userdata);

final class ggml_opt_optimizer_params extends ffi.Struct {
  external UnnamedStruct adamw;

  external UnnamedStruct$1 sgd;
}

enum ggml_opt_optimizer_type {
  GGML_OPT_OPTIMIZER_TYPE_ADAMW(0),
  GGML_OPT_OPTIMIZER_TYPE_SGD(1),
  GGML_OPT_OPTIMIZER_TYPE_COUNT(2);

  final int value;
  const ggml_opt_optimizer_type(this.value);

  static ggml_opt_optimizer_type fromValue(int value) => switch (value) {
    0 => GGML_OPT_OPTIMIZER_TYPE_ADAMW,
    1 => GGML_OPT_OPTIMIZER_TYPE_SGD,
    2 => GGML_OPT_OPTIMIZER_TYPE_COUNT,
    _ => throw ArgumentError(
      'Unknown value for ggml_opt_optimizer_type: $value',
    ),
  };
}

final class ggml_opt_result extends ffi.Opaque {}

typedef ggml_opt_result_t = ffi.Pointer<ggml_opt_result>;

final class ggml_tensor extends ffi.Struct {
  @ffi.UnsignedInt()
  external int typeAsInt;

  ggml_type get type => ggml_type.fromValue(typeAsInt);

  external ffi.Pointer<ggml_backend_buffer> buffer;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Int64> ne;

  @ffi.Array.multi([4])
  external ffi.Array<ffi.Size> nb;

  @ffi.UnsignedInt()
  external int opAsInt;

  ggml_op get op => ggml_op.fromValue(opAsInt);

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Int32> op_params;

  @ffi.Int32()
  external int flags;

  @ffi.Array.multi([10])
  external ffi.Array<ffi.Pointer<ggml_tensor>> src;

  external ffi.Pointer<ggml_tensor> view_src;

  @ffi.Size()
  external int view_offs;

  external ffi.Pointer<ffi.Void> data;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> name;

  external ffi.Pointer<ffi.Void> extra;

  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> padding;
}

final class ggml_threadpool extends ffi.Opaque {}

typedef ggml_threadpool_t = ffi.Pointer<ggml_threadpool>;

enum ggml_type {
  GGML_TYPE_F32(0),
  GGML_TYPE_F16(1),
  GGML_TYPE_Q4_0(2),
  GGML_TYPE_Q4_1(3),
  GGML_TYPE_Q5_0(6),
  GGML_TYPE_Q5_1(7),
  GGML_TYPE_Q8_0(8),
  GGML_TYPE_Q8_1(9),
  GGML_TYPE_Q2_K(10),
  GGML_TYPE_Q3_K(11),
  GGML_TYPE_Q4_K(12),
  GGML_TYPE_Q5_K(13),
  GGML_TYPE_Q6_K(14),
  GGML_TYPE_Q8_K(15),
  GGML_TYPE_IQ2_XXS(16),
  GGML_TYPE_IQ2_XS(17),
  GGML_TYPE_IQ3_XXS(18),
  GGML_TYPE_IQ1_S(19),
  GGML_TYPE_IQ4_NL(20),
  GGML_TYPE_IQ3_S(21),
  GGML_TYPE_IQ2_S(22),
  GGML_TYPE_IQ4_XS(23),
  GGML_TYPE_I8(24),
  GGML_TYPE_I16(25),
  GGML_TYPE_I32(26),
  GGML_TYPE_I64(27),
  GGML_TYPE_F64(28),
  GGML_TYPE_IQ1_M(29),
  GGML_TYPE_BF16(30),
  GGML_TYPE_TQ1_0(34),
  GGML_TYPE_TQ2_0(35),
  GGML_TYPE_MXFP4(39),
  GGML_TYPE_NVFP4(40),
  GGML_TYPE_COUNT(41);

  final int value;
  const ggml_type(this.value);

  static ggml_type fromValue(int value) => switch (value) {
    0 => GGML_TYPE_F32,
    1 => GGML_TYPE_F16,
    2 => GGML_TYPE_Q4_0,
    3 => GGML_TYPE_Q4_1,
    6 => GGML_TYPE_Q5_0,
    7 => GGML_TYPE_Q5_1,
    8 => GGML_TYPE_Q8_0,
    9 => GGML_TYPE_Q8_1,
    10 => GGML_TYPE_Q2_K,
    11 => GGML_TYPE_Q3_K,
    12 => GGML_TYPE_Q4_K,
    13 => GGML_TYPE_Q5_K,
    14 => GGML_TYPE_Q6_K,
    15 => GGML_TYPE_Q8_K,
    16 => GGML_TYPE_IQ2_XXS,
    17 => GGML_TYPE_IQ2_XS,
    18 => GGML_TYPE_IQ3_XXS,
    19 => GGML_TYPE_IQ1_S,
    20 => GGML_TYPE_IQ4_NL,
    21 => GGML_TYPE_IQ3_S,
    22 => GGML_TYPE_IQ2_S,
    23 => GGML_TYPE_IQ4_XS,
    24 => GGML_TYPE_I8,
    25 => GGML_TYPE_I16,
    26 => GGML_TYPE_I32,
    27 => GGML_TYPE_I64,
    28 => GGML_TYPE_F64,
    29 => GGML_TYPE_IQ1_M,
    30 => GGML_TYPE_BF16,
    34 => GGML_TYPE_TQ1_0,
    35 => GGML_TYPE_TQ2_0,
    39 => GGML_TYPE_MXFP4,
    40 => GGML_TYPE_NVFP4,
    41 => GGML_TYPE_COUNT,
    _ => throw ArgumentError('Unknown value for ggml_type: $value'),
  };
}

final class gguf_context extends ffi.Opaque {}

final class llama_adapter_lora extends ffi.Opaque {}

enum llama_attention_type {
  LLAMA_ATTENTION_TYPE_UNSPECIFIED(-1),
  LLAMA_ATTENTION_TYPE_CAUSAL(0),
  LLAMA_ATTENTION_TYPE_NON_CAUSAL(1);

  final int value;
  const llama_attention_type(this.value);

  static llama_attention_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ATTENTION_TYPE_UNSPECIFIED,
    0 => LLAMA_ATTENTION_TYPE_CAUSAL,
    1 => LLAMA_ATTENTION_TYPE_NON_CAUSAL,
    _ => throw ArgumentError('Unknown value for llama_attention_type: $value'),
  };
}

final class llama_batch extends ffi.Struct {
  @ffi.Int32()
  external int n_tokens;

  external ffi.Pointer<llama_token> token;

  external ffi.Pointer<ffi.Float> embd;

  external ffi.Pointer<llama_pos> pos;

  external ffi.Pointer<ffi.Int32> n_seq_id;

  external ffi.Pointer<ffi.Pointer<llama_seq_id>> seq_id;

  external ffi.Pointer<ffi.Int8> logits;
}

final class llama_chat_message extends ffi.Struct {
  external ffi.Pointer<ffi.Char> role;

  external ffi.Pointer<ffi.Char> content;
}

final class llama_context extends ffi.Opaque {}

final class llama_context_params extends ffi.Struct {
  @ffi.Uint32()
  external int n_ctx;

  @ffi.Uint32()
  external int n_batch;

  @ffi.Uint32()
  external int n_ubatch;

  @ffi.Uint32()
  external int n_seq_max;

  @ffi.Int32()
  external int n_threads;

  @ffi.Int32()
  external int n_threads_batch;

  @ffi.Int()
  external int rope_scaling_typeAsInt;

  llama_rope_scaling_type get rope_scaling_type =>
      llama_rope_scaling_type.fromValue(rope_scaling_typeAsInt);

  @ffi.Int()
  external int pooling_typeAsInt;

  llama_pooling_type get pooling_type =>
      llama_pooling_type.fromValue(pooling_typeAsInt);

  @ffi.Int()
  external int attention_typeAsInt;

  llama_attention_type get attention_type =>
      llama_attention_type.fromValue(attention_typeAsInt);

  @ffi.Int()
  external int flash_attn_typeAsInt;

  llama_flash_attn_type get flash_attn_type =>
      llama_flash_attn_type.fromValue(flash_attn_typeAsInt);

  @ffi.Float()
  external double rope_freq_base;

  @ffi.Float()
  external double rope_freq_scale;

  @ffi.Float()
  external double yarn_ext_factor;

  @ffi.Float()
  external double yarn_attn_factor;

  @ffi.Float()
  external double yarn_beta_fast;

  @ffi.Float()
  external double yarn_beta_slow;

  @ffi.Uint32()
  external int yarn_orig_ctx;

  @ffi.Float()
  external double defrag_thold;

  external ggml_backend_sched_eval_callback cb_eval;

  external ffi.Pointer<ffi.Void> cb_eval_user_data;

  @ffi.UnsignedInt()
  external int type_kAsInt;

  ggml_type get type_k => ggml_type.fromValue(type_kAsInt);

  @ffi.UnsignedInt()
  external int type_vAsInt;

  ggml_type get type_v => ggml_type.fromValue(type_vAsInt);

  external ggml_abort_callback abort_callback;

  external ffi.Pointer<ffi.Void> abort_callback_data;

  @ffi.Bool()
  external bool embeddings;

  @ffi.Bool()
  external bool offload_kqv;

  @ffi.Bool()
  external bool no_perf;

  @ffi.Bool()
  external bool op_offload;

  @ffi.Bool()
  external bool swa_full;

  @ffi.Bool()
  external bool kv_unified;

  external ffi.Pointer<llama_sampler_seq_config> samplers;

  @ffi.Size()
  external int n_samplers;
}

enum llama_flash_attn_type {
  LLAMA_FLASH_ATTN_TYPE_AUTO(-1),
  LLAMA_FLASH_ATTN_TYPE_DISABLED(0),
  LLAMA_FLASH_ATTN_TYPE_ENABLED(1);

  final int value;
  const llama_flash_attn_type(this.value);

  static llama_flash_attn_type fromValue(int value) => switch (value) {
    -1 => LLAMA_FLASH_ATTN_TYPE_AUTO,
    0 => LLAMA_FLASH_ATTN_TYPE_DISABLED,
    1 => LLAMA_FLASH_ATTN_TYPE_ENABLED,
    _ => throw ArgumentError('Unknown value for llama_flash_attn_type: $value'),
  };
}

enum llama_ftype {
  LLAMA_FTYPE_ALL_F32(0),
  LLAMA_FTYPE_MOSTLY_F16(1),
  LLAMA_FTYPE_MOSTLY_Q4_0(2),
  LLAMA_FTYPE_MOSTLY_Q4_1(3),
  LLAMA_FTYPE_MOSTLY_Q8_0(7),
  LLAMA_FTYPE_MOSTLY_Q5_0(8),
  LLAMA_FTYPE_MOSTLY_Q5_1(9),
  LLAMA_FTYPE_MOSTLY_Q2_K(10),
  LLAMA_FTYPE_MOSTLY_Q3_K_S(11),
  LLAMA_FTYPE_MOSTLY_Q3_K_M(12),
  LLAMA_FTYPE_MOSTLY_Q3_K_L(13),
  LLAMA_FTYPE_MOSTLY_Q4_K_S(14),
  LLAMA_FTYPE_MOSTLY_Q4_K_M(15),
  LLAMA_FTYPE_MOSTLY_Q5_K_S(16),
  LLAMA_FTYPE_MOSTLY_Q5_K_M(17),
  LLAMA_FTYPE_MOSTLY_Q6_K(18),
  LLAMA_FTYPE_MOSTLY_IQ2_XXS(19),
  LLAMA_FTYPE_MOSTLY_IQ2_XS(20),
  LLAMA_FTYPE_MOSTLY_Q2_K_S(21),
  LLAMA_FTYPE_MOSTLY_IQ3_XS(22),
  LLAMA_FTYPE_MOSTLY_IQ3_XXS(23),
  LLAMA_FTYPE_MOSTLY_IQ1_S(24),
  LLAMA_FTYPE_MOSTLY_IQ4_NL(25),
  LLAMA_FTYPE_MOSTLY_IQ3_S(26),
  LLAMA_FTYPE_MOSTLY_IQ3_M(27),
  LLAMA_FTYPE_MOSTLY_IQ2_S(28),
  LLAMA_FTYPE_MOSTLY_IQ2_M(29),
  LLAMA_FTYPE_MOSTLY_IQ4_XS(30),
  LLAMA_FTYPE_MOSTLY_IQ1_M(31),
  LLAMA_FTYPE_MOSTLY_BF16(32),
  LLAMA_FTYPE_MOSTLY_TQ1_0(36),
  LLAMA_FTYPE_MOSTLY_TQ2_0(37),
  LLAMA_FTYPE_MOSTLY_MXFP4_MOE(38),
  LLAMA_FTYPE_MOSTLY_NVFP4(39),
  LLAMA_FTYPE_GUESSED(1024);

  final int value;
  const llama_ftype(this.value);

  static llama_ftype fromValue(int value) => switch (value) {
    0 => LLAMA_FTYPE_ALL_F32,
    1 => LLAMA_FTYPE_MOSTLY_F16,
    2 => LLAMA_FTYPE_MOSTLY_Q4_0,
    3 => LLAMA_FTYPE_MOSTLY_Q4_1,
    7 => LLAMA_FTYPE_MOSTLY_Q8_0,
    8 => LLAMA_FTYPE_MOSTLY_Q5_0,
    9 => LLAMA_FTYPE_MOSTLY_Q5_1,
    10 => LLAMA_FTYPE_MOSTLY_Q2_K,
    11 => LLAMA_FTYPE_MOSTLY_Q3_K_S,
    12 => LLAMA_FTYPE_MOSTLY_Q3_K_M,
    13 => LLAMA_FTYPE_MOSTLY_Q3_K_L,
    14 => LLAMA_FTYPE_MOSTLY_Q4_K_S,
    15 => LLAMA_FTYPE_MOSTLY_Q4_K_M,
    16 => LLAMA_FTYPE_MOSTLY_Q5_K_S,
    17 => LLAMA_FTYPE_MOSTLY_Q5_K_M,
    18 => LLAMA_FTYPE_MOSTLY_Q6_K,
    19 => LLAMA_FTYPE_MOSTLY_IQ2_XXS,
    20 => LLAMA_FTYPE_MOSTLY_IQ2_XS,
    21 => LLAMA_FTYPE_MOSTLY_Q2_K_S,
    22 => LLAMA_FTYPE_MOSTLY_IQ3_XS,
    23 => LLAMA_FTYPE_MOSTLY_IQ3_XXS,
    24 => LLAMA_FTYPE_MOSTLY_IQ1_S,
    25 => LLAMA_FTYPE_MOSTLY_IQ4_NL,
    26 => LLAMA_FTYPE_MOSTLY_IQ3_S,
    27 => LLAMA_FTYPE_MOSTLY_IQ3_M,
    28 => LLAMA_FTYPE_MOSTLY_IQ2_S,
    29 => LLAMA_FTYPE_MOSTLY_IQ2_M,
    30 => LLAMA_FTYPE_MOSTLY_IQ4_XS,
    31 => LLAMA_FTYPE_MOSTLY_IQ1_M,
    32 => LLAMA_FTYPE_MOSTLY_BF16,
    36 => LLAMA_FTYPE_MOSTLY_TQ1_0,
    37 => LLAMA_FTYPE_MOSTLY_TQ2_0,
    38 => LLAMA_FTYPE_MOSTLY_MXFP4_MOE,
    39 => LLAMA_FTYPE_MOSTLY_NVFP4,
    1024 => LLAMA_FTYPE_GUESSED,
    _ => throw ArgumentError('Unknown value for llama_ftype: $value'),
  };
}

final class llama_logit_bias extends ffi.Struct {
  @llama_token()
  external int token;

  @ffi.Float()
  external double bias;
}

final class llama_memory_i extends ffi.Opaque {}

typedef llama_memory_t = ffi.Pointer<llama_memory_i>;

final class llama_model extends ffi.Opaque {}

final class llama_model_imatrix_data extends ffi.Struct {
  external ffi.Pointer<ffi.Char> name;

  external ffi.Pointer<ffi.Float> data;

  @ffi.Size()
  external int size;
}

final class llama_model_kv_override extends ffi.Struct {
  @ffi.UnsignedInt()
  external int tagAsInt;

  llama_model_kv_override_type get tag =>
      llama_model_kv_override_type.fromValue(tagAsInt);

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> key;

  external UnnamedUnion unnamed;
}

enum llama_model_kv_override_type {
  LLAMA_KV_OVERRIDE_TYPE_INT(0),
  LLAMA_KV_OVERRIDE_TYPE_FLOAT(1),
  LLAMA_KV_OVERRIDE_TYPE_BOOL(2),
  LLAMA_KV_OVERRIDE_TYPE_STR(3);

  final int value;
  const llama_model_kv_override_type(this.value);

  static llama_model_kv_override_type fromValue(int value) => switch (value) {
    0 => LLAMA_KV_OVERRIDE_TYPE_INT,
    1 => LLAMA_KV_OVERRIDE_TYPE_FLOAT,
    2 => LLAMA_KV_OVERRIDE_TYPE_BOOL,
    3 => LLAMA_KV_OVERRIDE_TYPE_STR,
    _ => throw ArgumentError(
      'Unknown value for llama_model_kv_override_type: $value',
    ),
  };
}

enum llama_model_meta_key {
  LLAMA_MODEL_META_KEY_SAMPLING_SEQUENCE(0),
  LLAMA_MODEL_META_KEY_SAMPLING_TOP_K(1),
  LLAMA_MODEL_META_KEY_SAMPLING_TOP_P(2),
  LLAMA_MODEL_META_KEY_SAMPLING_MIN_P(3),
  LLAMA_MODEL_META_KEY_SAMPLING_XTC_PROBABILITY(4),
  LLAMA_MODEL_META_KEY_SAMPLING_XTC_THRESHOLD(5),
  LLAMA_MODEL_META_KEY_SAMPLING_TEMP(6),
  LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_LAST_N(7),
  LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_REPEAT(8),
  LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT(9),
  LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_TAU(10),
  LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_ETA(11);

  final int value;
  const llama_model_meta_key(this.value);

  static llama_model_meta_key fromValue(int value) => switch (value) {
    0 => LLAMA_MODEL_META_KEY_SAMPLING_SEQUENCE,
    1 => LLAMA_MODEL_META_KEY_SAMPLING_TOP_K,
    2 => LLAMA_MODEL_META_KEY_SAMPLING_TOP_P,
    3 => LLAMA_MODEL_META_KEY_SAMPLING_MIN_P,
    4 => LLAMA_MODEL_META_KEY_SAMPLING_XTC_PROBABILITY,
    5 => LLAMA_MODEL_META_KEY_SAMPLING_XTC_THRESHOLD,
    6 => LLAMA_MODEL_META_KEY_SAMPLING_TEMP,
    7 => LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_LAST_N,
    8 => LLAMA_MODEL_META_KEY_SAMPLING_PENALTY_REPEAT,
    9 => LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT,
    10 => LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_TAU,
    11 => LLAMA_MODEL_META_KEY_SAMPLING_MIROSTAT_ETA,
    _ => throw ArgumentError('Unknown value for llama_model_meta_key: $value'),
  };
}

final class llama_model_params extends ffi.Struct {
  external ffi.Pointer<ggml_backend_dev_t> devices;

  external ffi.Pointer<llama_model_tensor_buft_override> tensor_buft_overrides;

  @ffi.Int32()
  external int n_gpu_layers;

  @ffi.UnsignedInt()
  external int split_modeAsInt;

  llama_split_mode get split_mode =>
      llama_split_mode.fromValue(split_modeAsInt);

  @ffi.Int32()
  external int main_gpu;

  external ffi.Pointer<ffi.Float> tensor_split;

  external llama_progress_callback progress_callback;

  external ffi.Pointer<ffi.Void> progress_callback_user_data;

  external ffi.Pointer<llama_model_kv_override> kv_overrides;

  @ffi.Bool()
  external bool vocab_only;

  @ffi.Bool()
  external bool use_mmap;

  @ffi.Bool()
  external bool use_direct_io;

  @ffi.Bool()
  external bool use_mlock;

  @ffi.Bool()
  external bool check_tensors;

  @ffi.Bool()
  external bool use_extra_bufts;

  @ffi.Bool()
  external bool no_host;

  @ffi.Bool()
  external bool no_alloc;
}

final class llama_model_quantize_params extends ffi.Struct {
  @ffi.Int32()
  external int nthread;

  @ffi.UnsignedInt()
  external int ftypeAsInt;

  llama_ftype get ftype => llama_ftype.fromValue(ftypeAsInt);

  @ffi.UnsignedInt()
  external int output_tensor_typeAsInt;

  ggml_type get output_tensor_type =>
      ggml_type.fromValue(output_tensor_typeAsInt);

  @ffi.UnsignedInt()
  external int token_embedding_typeAsInt;

  ggml_type get token_embedding_type =>
      ggml_type.fromValue(token_embedding_typeAsInt);

  @ffi.Bool()
  external bool allow_requantize;

  @ffi.Bool()
  external bool quantize_output_tensor;

  @ffi.Bool()
  external bool only_copy;

  @ffi.Bool()
  external bool pure;

  @ffi.Bool()
  external bool keep_split;

  @ffi.Bool()
  external bool dry_run;

  external ffi.Pointer<llama_model_imatrix_data> imatrix;

  external ffi.Pointer<llama_model_kv_override> kv_overrides;

  external ffi.Pointer<llama_model_tensor_override> tt_overrides;

  external ffi.Pointer<ffi.Int32> prune_layers;
}

typedef llama_model_set_tensor_data_t =
    ffi.Pointer<ffi.NativeFunction<llama_model_set_tensor_data_tFunction>>;
typedef llama_model_set_tensor_data_tFunction =
    ffi.Void Function(
      ffi.Pointer<ggml_tensor> tensor,
      ffi.Pointer<ffi.Void> userdata,
    );
typedef Dartllama_model_set_tensor_data_tFunction =
    void Function(
      ffi.Pointer<ggml_tensor> tensor,
      ffi.Pointer<ffi.Void> userdata,
    );

final class llama_model_tensor_buft_override extends ffi.Struct {
  external ffi.Pointer<ffi.Char> pattern;

  external ggml_backend_buffer_type_t buft;
}

final class llama_model_tensor_override extends ffi.Struct {
  external ffi.Pointer<ffi.Char> pattern;

  @ffi.UnsignedInt()
  external int typeAsInt;

  ggml_type get type => ggml_type.fromValue(typeAsInt);
}

typedef llama_opt_param_filter =
    ffi.Pointer<ffi.NativeFunction<llama_opt_param_filterFunction>>;
typedef llama_opt_param_filterFunction =
    ffi.Bool Function(
      ffi.Pointer<ggml_tensor> tensor,
      ffi.Pointer<ffi.Void> userdata,
    );
typedef Dartllama_opt_param_filterFunction =
    bool Function(
      ffi.Pointer<ggml_tensor> tensor,
      ffi.Pointer<ffi.Void> userdata,
    );

final class llama_opt_params extends ffi.Struct {
  @ffi.Uint32()
  external int n_ctx_train;

  external llama_opt_param_filter param_filter;

  external ffi.Pointer<ffi.Void> param_filter_ud;

  external ggml_opt_get_optimizer_params get_opt_pars;

  external ffi.Pointer<ffi.Void> get_opt_pars_ud;

  @ffi.UnsignedInt()
  external int optimizer_typeAsInt;

  ggml_opt_optimizer_type get optimizer_type =>
      ggml_opt_optimizer_type.fromValue(optimizer_typeAsInt);
}

enum llama_params_fit_status {
  LLAMA_PARAMS_FIT_STATUS_SUCCESS(0),
  LLAMA_PARAMS_FIT_STATUS_FAILURE(1),
  LLAMA_PARAMS_FIT_STATUS_ERROR(2);

  final int value;
  const llama_params_fit_status(this.value);

  static llama_params_fit_status fromValue(int value) => switch (value) {
    0 => LLAMA_PARAMS_FIT_STATUS_SUCCESS,
    1 => LLAMA_PARAMS_FIT_STATUS_FAILURE,
    2 => LLAMA_PARAMS_FIT_STATUS_ERROR,
    _ => throw ArgumentError(
      'Unknown value for llama_params_fit_status: $value',
    ),
  };
}

final class llama_perf_context_data extends ffi.Struct {
  @ffi.Double()
  external double t_start_ms;

  @ffi.Double()
  external double t_load_ms;

  @ffi.Double()
  external double t_p_eval_ms;

  @ffi.Double()
  external double t_eval_ms;

  @ffi.Int32()
  external int n_p_eval;

  @ffi.Int32()
  external int n_eval;

  @ffi.Int32()
  external int n_reused;
}

final class llama_perf_sampler_data extends ffi.Struct {
  @ffi.Double()
  external double t_sample_ms;

  @ffi.Int32()
  external int n_sample;
}

enum llama_pooling_type {
  LLAMA_POOLING_TYPE_UNSPECIFIED(-1),
  LLAMA_POOLING_TYPE_NONE(0),
  LLAMA_POOLING_TYPE_MEAN(1),
  LLAMA_POOLING_TYPE_CLS(2),
  LLAMA_POOLING_TYPE_LAST(3),
  LLAMA_POOLING_TYPE_RANK(4);

  final int value;
  const llama_pooling_type(this.value);

  static llama_pooling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_POOLING_TYPE_UNSPECIFIED,
    0 => LLAMA_POOLING_TYPE_NONE,
    1 => LLAMA_POOLING_TYPE_MEAN,
    2 => LLAMA_POOLING_TYPE_CLS,
    3 => LLAMA_POOLING_TYPE_LAST,
    4 => LLAMA_POOLING_TYPE_RANK,
    _ => throw ArgumentError('Unknown value for llama_pooling_type: $value'),
  };
}

typedef llama_pos = ffi.Int32;
typedef Dartllama_pos = int;
typedef llama_progress_callback =
    ffi.Pointer<ffi.NativeFunction<llama_progress_callbackFunction>>;
typedef llama_progress_callbackFunction =
    ffi.Bool Function(ffi.Float progress, ffi.Pointer<ffi.Void> user_data);
typedef Dartllama_progress_callbackFunction =
    bool Function(double progress, ffi.Pointer<ffi.Void> user_data);

enum llama_rope_scaling_type {
  LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED(-1),
  LLAMA_ROPE_SCALING_TYPE_NONE(0),
  LLAMA_ROPE_SCALING_TYPE_LINEAR(1),
  LLAMA_ROPE_SCALING_TYPE_YARN(2),
  LLAMA_ROPE_SCALING_TYPE_LONGROPE(3);

  static const LLAMA_ROPE_SCALING_TYPE_MAX_VALUE =
      LLAMA_ROPE_SCALING_TYPE_LONGROPE;

  final int value;
  const llama_rope_scaling_type(this.value);

  static llama_rope_scaling_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ROPE_SCALING_TYPE_UNSPECIFIED,
    0 => LLAMA_ROPE_SCALING_TYPE_NONE,
    1 => LLAMA_ROPE_SCALING_TYPE_LINEAR,
    2 => LLAMA_ROPE_SCALING_TYPE_YARN,
    3 => LLAMA_ROPE_SCALING_TYPE_LONGROPE,
    _ => throw ArgumentError(
      'Unknown value for llama_rope_scaling_type: $value',
    ),
  };

  @override
  String toString() {
    if (this == LLAMA_ROPE_SCALING_TYPE_LONGROPE)
      return "llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_LONGROPE, llama_rope_scaling_type.LLAMA_ROPE_SCALING_TYPE_MAX_VALUE";
    return super.toString();
  }
}

enum llama_rope_type {
  LLAMA_ROPE_TYPE_NONE(-1),
  LLAMA_ROPE_TYPE_NORM(0),
  LLAMA_ROPE_TYPE_NEOX(2),
  LLAMA_ROPE_TYPE_MROPE(8),
  LLAMA_ROPE_TYPE_IMROPE(40),
  LLAMA_ROPE_TYPE_VISION(24);

  final int value;
  const llama_rope_type(this.value);

  static llama_rope_type fromValue(int value) => switch (value) {
    -1 => LLAMA_ROPE_TYPE_NONE,
    0 => LLAMA_ROPE_TYPE_NORM,
    2 => LLAMA_ROPE_TYPE_NEOX,
    8 => LLAMA_ROPE_TYPE_MROPE,
    40 => LLAMA_ROPE_TYPE_IMROPE,
    24 => LLAMA_ROPE_TYPE_VISION,
    _ => throw ArgumentError('Unknown value for llama_rope_type: $value'),
  };
}

final class llama_sampler extends ffi.Struct {
  external ffi.Pointer<llama_sampler_i> iface;

  external llama_sampler_context_t ctx;
}

final class llama_sampler_chain_params extends ffi.Struct {
  @ffi.Bool()
  external bool no_perf;
}

typedef llama_sampler_context_t = ffi.Pointer<ffi.Void>;

final class llama_sampler_data extends ffi.Struct {
  external ffi.Pointer<ggml_tensor> logits;

  external ffi.Pointer<ggml_tensor> probs;

  external ffi.Pointer<ggml_tensor> sampled;

  external ffi.Pointer<ggml_tensor> candidates;
}

final class llama_sampler_i extends ffi.Struct {
  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Char> Function(ffi.Pointer<llama_sampler> smpl)
    >
  >
  name;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<llama_sampler> smpl, llama_token token)
    >
  >
  accept;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<llama_sampler> smpl,
        ffi.Pointer<llama_token_data_array> cur_p,
      )
    >
  >
  apply;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_sampler> smpl)>
  >
  reset;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<llama_sampler> Function(ffi.Pointer<llama_sampler> smpl)
    >
  >
  clone;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_sampler> smpl)>
  >
  free;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Bool Function(
        ffi.Pointer<llama_sampler> smpl,
        ggml_backend_buffer_type_t buft,
      )
    >
  >
  backend_init;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<llama_sampler> smpl,
        ffi.Pointer<ggml_context> ctx,
        ffi.Pointer<ggml_cgraph> gf,
        ffi.Pointer<ggml_tensor> selected_token,
      )
    >
  >
  backend_accept;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<llama_sampler> smpl,
        ffi.Pointer<ggml_context> ctx,
        ffi.Pointer<ggml_cgraph> gf,
        ffi.Pointer<llama_sampler_data> data,
      )
    >
  >
  backend_apply;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<llama_sampler> smpl)>
  >
  backend_set_input;
}

final class llama_sampler_seq_config extends ffi.Struct {
  @llama_seq_id()
  external int seq_id;

  external ffi.Pointer<llama_sampler> sampler;
}

typedef llama_seq_id = ffi.Int32;
typedef Dartllama_seq_id = int;

enum llama_split_mode {
  LLAMA_SPLIT_MODE_NONE(0),
  LLAMA_SPLIT_MODE_LAYER(1),
  LLAMA_SPLIT_MODE_ROW(2);

  final int value;
  const llama_split_mode(this.value);

  static llama_split_mode fromValue(int value) => switch (value) {
    0 => LLAMA_SPLIT_MODE_NONE,
    1 => LLAMA_SPLIT_MODE_LAYER,
    2 => LLAMA_SPLIT_MODE_ROW,
    _ => throw ArgumentError('Unknown value for llama_split_mode: $value'),
  };
}

typedef llama_state_seq_flags = ffi.Uint32;
typedef Dartllama_state_seq_flags = int;
typedef llama_token = ffi.Int32;
typedef Dartllama_token = int;

enum llama_token_attr {
  LLAMA_TOKEN_ATTR_UNDEFINED(0),
  LLAMA_TOKEN_ATTR_UNKNOWN(1),
  LLAMA_TOKEN_ATTR_UNUSED(2),
  LLAMA_TOKEN_ATTR_NORMAL(4),
  LLAMA_TOKEN_ATTR_CONTROL(8),
  LLAMA_TOKEN_ATTR_USER_DEFINED(16),
  LLAMA_TOKEN_ATTR_BYTE(32),
  LLAMA_TOKEN_ATTR_NORMALIZED(64),
  LLAMA_TOKEN_ATTR_LSTRIP(128),
  LLAMA_TOKEN_ATTR_RSTRIP(256),
  LLAMA_TOKEN_ATTR_SINGLE_WORD(512);

  final int value;
  const llama_token_attr(this.value);

  static llama_token_attr fromValue(int value) => switch (value) {
    0 => LLAMA_TOKEN_ATTR_UNDEFINED,
    1 => LLAMA_TOKEN_ATTR_UNKNOWN,
    2 => LLAMA_TOKEN_ATTR_UNUSED,
    4 => LLAMA_TOKEN_ATTR_NORMAL,
    8 => LLAMA_TOKEN_ATTR_CONTROL,
    16 => LLAMA_TOKEN_ATTR_USER_DEFINED,
    32 => LLAMA_TOKEN_ATTR_BYTE,
    64 => LLAMA_TOKEN_ATTR_NORMALIZED,
    128 => LLAMA_TOKEN_ATTR_LSTRIP,
    256 => LLAMA_TOKEN_ATTR_RSTRIP,
    512 => LLAMA_TOKEN_ATTR_SINGLE_WORD,
    _ => throw ArgumentError('Unknown value for llama_token_attr: $value'),
  };
}

final class llama_token_data extends ffi.Struct {
  @llama_token()
  external int id;

  @ffi.Float()
  external double logit;

  @ffi.Float()
  external double p;
}

final class llama_token_data_array extends ffi.Struct {
  external ffi.Pointer<llama_token_data> data;

  @ffi.Size()
  external int size;

  @ffi.Int64()
  external int selected;

  @ffi.Bool()
  external bool sorted;
}

enum llama_token_type {
  LLAMA_TOKEN_TYPE_UNDEFINED(0),
  LLAMA_TOKEN_TYPE_NORMAL(1),
  LLAMA_TOKEN_TYPE_UNKNOWN(2),
  LLAMA_TOKEN_TYPE_CONTROL(3),
  LLAMA_TOKEN_TYPE_USER_DEFINED(4),
  LLAMA_TOKEN_TYPE_UNUSED(5),
  LLAMA_TOKEN_TYPE_BYTE(6);

  final int value;
  const llama_token_type(this.value);

  static llama_token_type fromValue(int value) => switch (value) {
    0 => LLAMA_TOKEN_TYPE_UNDEFINED,
    1 => LLAMA_TOKEN_TYPE_NORMAL,
    2 => LLAMA_TOKEN_TYPE_UNKNOWN,
    3 => LLAMA_TOKEN_TYPE_CONTROL,
    4 => LLAMA_TOKEN_TYPE_USER_DEFINED,
    5 => LLAMA_TOKEN_TYPE_UNUSED,
    6 => LLAMA_TOKEN_TYPE_BYTE,
    _ => throw ArgumentError('Unknown value for llama_token_type: $value'),
  };
}

final class llama_vocab extends ffi.Opaque {}

enum llama_vocab_type {
  LLAMA_VOCAB_TYPE_NONE(0),
  LLAMA_VOCAB_TYPE_SPM(1),
  LLAMA_VOCAB_TYPE_BPE(2),
  LLAMA_VOCAB_TYPE_WPM(3),
  LLAMA_VOCAB_TYPE_UGM(4),
  LLAMA_VOCAB_TYPE_RWKV(5),
  LLAMA_VOCAB_TYPE_PLAMO2(6);

  final int value;
  const llama_vocab_type(this.value);

  static llama_vocab_type fromValue(int value) => switch (value) {
    0 => LLAMA_VOCAB_TYPE_NONE,
    1 => LLAMA_VOCAB_TYPE_SPM,
    2 => LLAMA_VOCAB_TYPE_BPE,
    3 => LLAMA_VOCAB_TYPE_WPM,
    4 => LLAMA_VOCAB_TYPE_UGM,
    5 => LLAMA_VOCAB_TYPE_RWKV,
    6 => LLAMA_VOCAB_TYPE_PLAMO2,
    _ => throw ArgumentError('Unknown value for llama_vocab_type: $value'),
  };
}
